#!/bin/bash

if [ -z "$1" ]
	then
	NUM=$(((RANDOM%21)))
else
	NUM="$1"
fi

if [ -z "$2" ]
	then
	WIDTH=$(((RANDOM%3)+1))
else
	WIDTH="$2"
fi

case "$WIDTH" in
1)
GLANS="     _
    /|\ 
"

SHAFT="    | |
"

BALLS="   _| |_ 
  (_) (_)
"
;;
2)
GLANS="      _ _     
     / | \    
    (__*__)  
" 

SHAFT="    |     |   
"

BALLS="   ---._.---  
  /         \ 
  |    _    | 
  \    |    / 
   \__/ \__/  "
;;
3)
GLANS="              __ __
           .-\`  |  \`-.
          /     |     \ 
         (_____________)
"
SHAFT="          |           |
"
BALLS="       .-\` \`-._____.-\` \`-. 
      /                   \  
     /                     \  
     |                     |  
     \                     /  
      \                   /  
       \`-___--°°°°°--___-\`  
"
;;
esac

STRING="$GLANS"
for i in `seq 1 $NUM`;
do
	STRING="$STRING$SHAFT"
done
STRING="$STRING$BALLS"
echo "$STRING
";
RESULT="$((($NUM+1)*($WIDTH*$WIDTH)))"
echo "YOUR PENIS SCORE IS: $RESULT";
exit 1
